[package]
name = "rust-performance-tets"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
criterion = "=0.5.1"

[dev-dependencies]
criterion = "=0.5.1"

[[bench]]
name = "benchmark"
path = "src/benchmark.rs"
harness = false
